### PR TITLE
Use separate lifetimes to avoid false borrowing

### PR DESCRIPTION
**Pull request by bluss**

### CODE REVIEW

**Comment by bluss** [comment]
The example is not possible unless the API is updated to be more general. Using the same lifetime variable means that you tie together the two borrows, which is wrong (it's not what you actually want).

**Comment by est31** [comment]
:+1: Like it!

**Comment by bluss** [comment]
Updated to use lifetime elision. Maybe it's more confusing, but it's the idiomatic thing to do. It's also the least typing -- the default `&mut self -> &mut` does the right thing for us!

**Comment by SimonTeixidor** [comment]
Thank you. I doubt I would have spotted that error myself. Merged! :)

**Comment by bluss** [comment]
great.

**Comment by bluss** [comment]
You'd probably run into it eventually.

**Comment by SimonTeixidor** [comment]
I guess, yeah. Thank you anyways!

**Comment by bluss** [comment]
This was to help @est31, this crate came up in #rust.

**Comment by SimonTeixidor** [comment]
Aha, I saw the logs now. @est31: I think you're the first one to use this (apart from me, that is). Feel free to open an issue if you feel something is odd or some feature is missing. I'd love any feedback!

**Pull request merged**
